/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GridscoreDb extends SchemaImpl {

    private static final long serialVersionUID = -1940103847;

    /**
     * The reference instance of <code>gridscore_db</code>
     */
    public static final GridscoreDb GRIDSCORE_DB = new GridscoreDb();

    /**
     * No further instances allowed
     */
    private GridscoreDb() {
        super("gridscore_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
