/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen;


import javax.annotation.Generated;

import jhi.gridscore.server.database.codegen.tables.Configurations;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>gridscore_db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CONFIGURATIONS_CONFIGURATION_UUID = Indexes0.CONFIGURATIONS_CONFIGURATION_UUID;
    public static final Index CONFIGURATIONS_PRIMARY = Indexes0.CONFIGURATIONS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CONFIGURATIONS_CONFIGURATION_UUID = Internal.createIndex("configuration_uuid", Configurations.CONFIGURATIONS, new OrderField[] { Configurations.CONFIGURATIONS.UUID }, true);
        public static Index CONFIGURATIONS_PRIMARY = Internal.createIndex("PRIMARY", Configurations.CONFIGURATIONS, new OrderField[] { Configurations.CONFIGURATIONS.UUID }, true);
    }
}
