/*
 * This file is generated by jOOQ.
 */
package jhi.gridscore.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import jhi.gridscore.server.pojo.Configuration;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Configurations implements Serializable {

    private static final long serialVersionUID = 757821001;

    private String        uuid;
    private Configuration configuration;
    private Timestamp     createdOn;

    public Configurations() {}

    public Configurations(Configurations value) {
        this.uuid = value.uuid;
        this.configuration = value.configuration;
        this.createdOn = value.createdOn;
    }

    public Configurations(
        String        uuid,
        Configuration configuration,
        Timestamp     createdOn
    ) {
        this.uuid = uuid;
        this.configuration = configuration;
        this.createdOn = createdOn;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Configuration getConfiguration() {
        return this.configuration;
    }

    public void setConfiguration(Configuration configuration) {
        this.configuration = configuration;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Configurations (");

        sb.append(uuid);
        sb.append(", ").append(configuration);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
